services:
  postgres:
    image: postgres:17.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=andy
      - POSTGRES_DB=db
